package one.model;
// Generated Aug 12, 2020 6:31:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private Integer languageId;
     private String name;
     private Date lastUpdate;

    public Language() {
    }

    public Language(String name, Date lastUpdate) {
       this.name = name;
       this.lastUpdate = lastUpdate;
    
    }
   
    public Integer getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(Integer languageId) {
        this.languageId = languageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


